spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/Banking
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234